/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    media: Media;
    users: User;
    newsletter: Newsletter;
    'scheduled-emails': ScheduledEmail;
    orders: Order;
    'survey-responses': SurveyResponse;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-folders': FolderInterface;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    orders: {
      survey: 'survey-responses';
    };
    'payload-folders': {
      documentsAndFolders: 'payload-folders' | 'media';
    };
  };
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    newsletter: NewsletterSelect<false> | NewsletterSelect<true>;
    'scheduled-emails': ScheduledEmailsSelect<false> | ScheduledEmailsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'survey-responses': SurveyResponsesSelect<false> | SurveyResponsesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-folders': PayloadFoldersSelect<false> | PayloadFoldersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
    'survey-content': SurveyContent;
    'contact-content': ContactContent;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'survey-content': SurveyContentSelect<false> | SurveyContentSelect<true>;
    'contact-content': ContactContentSelect<false> | ContactContentSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: {
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * If checked, the page will be displayed as a text page
   */
  textPage?: boolean | null;
  hero?: {
    media?: (number | null) | Media;
    /**
     * Optional image shown while video loads. Use first frame of video for best results.
     */
    poster?: (number | null) | Media;
    title?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    add_subtitle?: boolean | null;
    subtitle?: string | null;
    add_button?: boolean | null;
    /**
     * test description
     */
    button_link?: {
      label?: string | null;
      url?: string | null;
    };
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | DelimiterBlock
    | ShopifyProductsBlock
    | ShopifyCartBlock
    | StepsBlock
    | PartnersBlock
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * When enabled, the slug will auto-generate from the title field on save and autosave.
   */
  generateSlug?: boolean | null;
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  folder?: (number | null) | FolderInterface;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders".
 */
export interface FolderInterface {
  id: number;
  name: string;
  folder?: (number | null) | FolderInterface;
  documentsAndFolders?: {
    docs?: (
      | {
          relationTo?: 'payload-folders';
          value: number | FolderInterface;
        }
      | {
          relationTo?: 'media';
          value: number | Media;
        }
    )[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  folderType?: 'media'[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  image?: (number | null) | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DelimiterBlock".
 */
export interface DelimiterBlock {
  fullWidth?: boolean | null;
  bottomPageDelimiter?: boolean | null;
  title?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'delimiterBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopifyProductsBlock".
 */
export interface ShopifyProductsBlock {
  'Limit info'?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'shopifyProductsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopifyCartBlock".
 */
export interface ShopifyCartBlock {
  emptyBasketLabel: string;
  selectedItemsLabel: string;
  additionalInfoLabel: string;
  companyDataLabel: string;
  formTipText: string;
  proceedToCheckoutLabel: string;
  deleteAllLabel: string;
  companyName: string;
  email: string;
  nip: string;
  website: string;
  city: string;
  completionDatePlaceholder: string;
  projectsPerYearPlaceholder: string;
  projectBudget: string;
  projectBudgetValues?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  projectTypePlaceholder: string;
  projectTypeOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  projectAreaPlaceholder: string;
  projectAreaValues?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  projectStagePlaceholder: string;
  projectStageOptions?:
    | {
        label: string;
        id?: string | null;
      }[]
    | null;
  consentText: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  consentText2: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'shopifyCartBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock".
 */
export interface StepsBlock {
  steps?:
    | {
        step: string;
        /**
         * More icons here: https://www.shadcn.io/icons
         */
        icon: number | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stepsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock".
 */
export interface PartnersBlock {
  partners?:
    | {
        partner?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'partnersBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter".
 */
export interface Newsletter {
  id: number;
  email?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-emails".
 */
export interface ScheduledEmail {
  id: number;
  linkedOrder: string | Order;
  linkedInternalOrder?: string | null;
  customerEmail: string;
  scheduledAt: string;
  expiresAt: string;
  status: 'pending' | 'sent' | 'failed' | 'cancelled';
  emailType: 'post_purchase_questions';
  token: string;
  isSurveyCompleted?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: string;
  hasSurvey?: boolean | null;
  survey?: {
    docs?: (number | SurveyResponse)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  email?: string | null;
  company_name?: string | null;
  projects_per_year?: string | null;
  city?: string | null;
  project_type?: string | null;
  completion_date?: string | null;
  project_stage?: string | null;
  project_area?: string | null;
  project_budget?: string | null;
  nip?: string | null;
  website?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-responses".
 */
export interface SurveyResponse {
  id: number;
  order: string | Order;
  linkedInternalOrder?: string | null;
  customer_email: string;
  completedAt: string;
  considered_brands?: string[] | null;
  rejected_brand?: string | null;
  brand_evaluations?:
    | {
        brand_name: string;
        rating: number;
        reasons?: string[] | null;
        other_reason?: string | null;
        id?: string | null;
      }[]
    | null;
  rejection_reasons?: string[] | null;
  rejection_other?: string | null;
  contact_request?: boolean | null;
  contact_brands?: string[] | null;
  missing_brands?: string | null;
  improvement_suggestion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'schedulePublish') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'newsletter';
        value: number | Newsletter;
      } | null)
    | ({
        relationTo: 'scheduled-emails';
        value: number | ScheduledEmail;
      } | null)
    | ({
        relationTo: 'survey-responses';
        value: number | SurveyResponse;
      } | null)
    | ({
        relationTo: 'payload-folders';
        value: number | FolderInterface;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  textPage?: T;
  hero?:
    | T
    | {
        media?: T;
        poster?: T;
        title?: T;
        add_subtitle?: T;
        subtitle?: T;
        add_button?: T;
        button_link?:
          | T
          | {
              label?: T;
              url?: T;
            };
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        delimiterBlock?: T | DelimiterBlockSelect<T>;
        shopifyProductsBlock?: T | ShopifyProductsBlockSelect<T>;
        shopifyCartBlock?: T | ShopifyCartBlockSelect<T>;
        stepsBlock?: T | StepsBlockSelect<T>;
        partnersBlock?: T | PartnersBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  generateSlug?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  image?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "DelimiterBlock_select".
 */
export interface DelimiterBlockSelect<T extends boolean = true> {
  fullWidth?: T;
  bottomPageDelimiter?: T;
  title?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopifyProductsBlock_select".
 */
export interface ShopifyProductsBlockSelect<T extends boolean = true> {
  'Limit info'?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ShopifyCartBlock_select".
 */
export interface ShopifyCartBlockSelect<T extends boolean = true> {
  emptyBasketLabel?: T;
  selectedItemsLabel?: T;
  additionalInfoLabel?: T;
  companyDataLabel?: T;
  formTipText?: T;
  proceedToCheckoutLabel?: T;
  deleteAllLabel?: T;
  companyName?: T;
  email?: T;
  nip?: T;
  website?: T;
  city?: T;
  completionDatePlaceholder?: T;
  projectsPerYearPlaceholder?: T;
  projectBudget?: T;
  projectBudgetValues?:
    | T
    | {
        label?: T;
        id?: T;
      };
  projectTypePlaceholder?: T;
  projectTypeOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  projectAreaPlaceholder?: T;
  projectAreaValues?:
    | T
    | {
        label?: T;
        id?: T;
      };
  projectStagePlaceholder?: T;
  projectStageOptions?:
    | T
    | {
        label?: T;
        id?: T;
      };
  consentText?: T;
  consentText2?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StepsBlock_select".
 */
export interface StepsBlockSelect<T extends boolean = true> {
  steps?:
    | T
    | {
        step?: T;
        icon?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "PartnersBlock_select".
 */
export interface PartnersBlockSelect<T extends boolean = true> {
  partners?:
    | T
    | {
        partner?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  folder?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter_select".
 */
export interface NewsletterSelect<T extends boolean = true> {
  email?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "scheduled-emails_select".
 */
export interface ScheduledEmailsSelect<T extends boolean = true> {
  linkedOrder?: T;
  linkedInternalOrder?: T;
  customerEmail?: T;
  scheduledAt?: T;
  expiresAt?: T;
  status?: T;
  emailType?: T;
  token?: T;
  isSurveyCompleted?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  id?: T;
  hasSurvey?: T;
  survey?: T;
  email?: T;
  company_name?: T;
  projects_per_year?: T;
  city?: T;
  project_type?: T;
  completion_date?: T;
  project_stage?: T;
  project_area?: T;
  project_budget?: T;
  nip?: T;
  website?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-responses_select".
 */
export interface SurveyResponsesSelect<T extends boolean = true> {
  order?: T;
  linkedInternalOrder?: T;
  customer_email?: T;
  completedAt?: T;
  considered_brands?: T;
  rejected_brand?: T;
  brand_evaluations?:
    | T
    | {
        brand_name?: T;
        rating?: T;
        reasons?: T;
        other_reason?: T;
        id?: T;
      };
  rejection_reasons?: T;
  rejection_other?: T;
  contact_request?: T;
  contact_brands?: T;
  missing_brands?: T;
  improvement_suggestion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-folders_select".
 */
export interface PayloadFoldersSelect<T extends boolean = true> {
  name?: T;
  folder?: T;
  documentsAndFolders?: T;
  folderType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-content".
 */
export interface SurveyContent {
  id: number;
  questions: {
    q1: {
      title: string;
      subtitle?: string | null;
    };
    q2: {
      title: string;
      subtitle?: string | null;
    };
    q3: {
      title: string;
      subtitle?: string | null;
    };
    q4: {
      title: string;
      subtitle?: string | null;
    };
    /**
     * Użyj {rejectedBrand} jako placeholder dla nazwy marki
     */
    q5: {
      title: string;
      subtitle?: string | null;
    };
    q6: {
      title: string;
      subtitle?: string | null;
    };
    q7: {
      title: string;
      subtitle?: string | null;
    };
    q8: {
      title: string;
      subtitle?: string | null;
    };
  };
  /**
   * Kolejność = wartość oceny (pierwszy = 1, ostatni = 5)
   */
  ratings?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Wartość rabatu w procentach (np. 10 = 10%)
   */
  discountPercentage: number;
  reasonsPositive?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  reasonsNegative?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  reasonsRejection?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  uiMessages: {
    toasts: {
      maxBrandsSelected: string;
      maxReasonsSelected: string;
      selectAtLeastOneBrand: string;
    };
    formLabels: {
      selectBrandOptional: string;
      noSuchBrandOption: string;
      yourAnswerPlaceholder: string;
      whichBrands: string;
      specifyExactly: string;
    };
    questionTexts: {
      positiveBrandQuestion: string;
      negativeBrandQuestion: string;
      selectMax2: string;
    };
    buttons: {
      yes: string;
      no: string;
      nextStep: string;
      sendSurvey: string;
    };
    discount: {
      welcomeDiscountTitle: string;
      discountSuccessMessage: string;
      discountFailureMessage: string;
    };
    dialog: {
      thankYouSurvey: string;
      yourCodeIs: string;
      sameCodeInEmail: string;
      goToMoodbox: string;
    };
    terms: {
      termsAcceptanceText: string;
    };
    errors: {
      fixErrorsBeforeSending: string;
    };
    header: {
      welcomeMessage: string;
      surveyTitle: string;
      surveyDescription: string;
      stepLabel: string;
      stepSeparator: string;
      totalSteps: string;
    };
    completed: {
      surveyAlreadyCompletedTitle: string;
      surveyAlreadyCompletedThankYou: string;
      surveyAlreadyCompletedInstructions: string;
      contactEmail: string;
    };
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content".
 */
export interface ContactContent {
  id: number;
  header: string;
  subjectPlaceholder: string;
  messagePlaceholder: string;
  emailPlaceholder: string;
  buttonText: string;
  /**
   * Optional additional content displayed below the form
   */
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "survey-content_select".
 */
export interface SurveyContentSelect<T extends boolean = true> {
  questions?:
    | T
    | {
        q1?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q2?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q3?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q4?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q5?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q6?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q7?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
        q8?:
          | T
          | {
              title?: T;
              subtitle?: T;
            };
      };
  ratings?:
    | T
    | {
        text?: T;
        id?: T;
      };
  discountPercentage?: T;
  reasonsPositive?:
    | T
    | {
        text?: T;
        id?: T;
      };
  reasonsNegative?:
    | T
    | {
        text?: T;
        id?: T;
      };
  reasonsRejection?:
    | T
    | {
        text?: T;
        id?: T;
      };
  uiMessages?:
    | T
    | {
        toasts?:
          | T
          | {
              maxBrandsSelected?: T;
              maxReasonsSelected?: T;
              selectAtLeastOneBrand?: T;
            };
        formLabels?:
          | T
          | {
              selectBrandOptional?: T;
              noSuchBrandOption?: T;
              yourAnswerPlaceholder?: T;
              whichBrands?: T;
              specifyExactly?: T;
            };
        questionTexts?:
          | T
          | {
              positiveBrandQuestion?: T;
              negativeBrandQuestion?: T;
              selectMax2?: T;
            };
        buttons?:
          | T
          | {
              yes?: T;
              no?: T;
              nextStep?: T;
              sendSurvey?: T;
            };
        discount?:
          | T
          | {
              welcomeDiscountTitle?: T;
              discountSuccessMessage?: T;
              discountFailureMessage?: T;
            };
        dialog?:
          | T
          | {
              thankYouSurvey?: T;
              yourCodeIs?: T;
              sameCodeInEmail?: T;
              goToMoodbox?: T;
            };
        terms?:
          | T
          | {
              termsAcceptanceText?: T;
            };
        errors?:
          | T
          | {
              fixErrorsBeforeSending?: T;
            };
        header?:
          | T
          | {
              welcomeMessage?: T;
              surveyTitle?: T;
              surveyDescription?: T;
              stepLabel?: T;
              stepSeparator?: T;
              totalSteps?: T;
            };
        completed?:
          | T
          | {
              surveyAlreadyCompletedTitle?: T;
              surveyAlreadyCompletedThankYou?: T;
              surveyAlreadyCompletedInstructions?: T;
              contactEmail?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-content_select".
 */
export interface ContactContentSelect<T extends boolean = true> {
  header?: T;
  subjectPlaceholder?: T;
  messagePlaceholder?: T;
  emailPlaceholder?: T;
  buttonText?: T;
  richText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?: {
      relationTo: 'pages';
      value: number | Page;
    } | null;
    global?: string | null;
    user?: (number | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}